"""
Outbound notification mail.

Used by the regenerate flow to tell the people sharing an RFQ that something
material changed. Nothing here may ever fail a run: every path returns a count
and logs, and callers treat a zero as "not sent", never as an error.
"""
from __future__ import annotations

import html
import re
import smtplib
import ssl
from email.message import EmailMessage
from email.utils import formataddr
from typing import Iterable, List

from .config import Settings

# Deliberately permissive: the aim is to drop obvious junk ("-", "n/a", a name
# with no @) before handing a list to the SMTP server, not to police addresses.
_EMAIL_RE = re.compile(r"^[^@\s,;]+@[^@\s,;]+\.[^@\s,;]+$")


def parse_recipients(raw: object) -> List[str]:
    """
    Split a shared-members value into addresses.

    Accepts a comma-separated string, a semicolon-separated one, a newline
    separated one, or a list. Trims, drops anything that is not shaped like an
    address, and de-duplicates case-insensitively while keeping the first
    spelling seen.
    """
    if raw is None:
        return []
    if isinstance(raw, str):
        candidates: Iterable[str] = re.split(r"[,;\n]", raw)
    elif isinstance(raw, (list, tuple, set)):
        candidates = [str(x) for x in raw]
    else:
        candidates = [str(raw)]

    out: List[str] = []
    seen = set()
    for item in candidates:
        addr = (item or "").strip().strip("<>").strip()
        if not addr or not _EMAIL_RE.match(addr):
            continue
        key = addr.lower()
        if key not in seen:
            seen.add(key)
            out.append(addr)
    return out


def _markdown_to_html(text: str) -> str:
    """
    Render the small markdown vocabulary the diff prompt emits: a `####`
    heading, `-` bullets and `**bold**`. Everything is escaped first, so model
    output and customer-supplied titles cannot inject markup.
    """
    lines = (text or "").splitlines()
    parts: List[str] = []
    in_list = False

    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        safe = html.escape(stripped)
        safe = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", safe)
        safe = re.sub(r"\*(.+?)\*", r"<em>\1</em>", safe)
        safe = re.sub(r"`(.+?)`", r"<code>\1</code>", safe)

        if stripped.startswith("####"):
            if in_list:
                parts.append("</ul>")
                in_list = False
            parts.append(
                f'<p style="margin:0 0 12px 0; font-size:16px; font-weight:bold; color:#1f2328;">'
                f'{safe.lstrip("# ").strip()}</p>'
            )
        elif stripped.startswith("- "):
            if not in_list:
                parts.append('<ul style="margin:0 0 12px 0; padding-left:20px;">')
                in_list = True
            parts.append(
                f'<li style="margin:0 0 8px 0; font-size:15px; line-height:24px; color:#33383f;">'
                f'{safe[2:]}</li>'
            )
        else:
            if in_list:
                parts.append("</ul>")
                in_list = False
            parts.append(
                f'<p style="margin:0 0 12px 0; font-size:15px; line-height:24px; color:#33383f;">{safe}</p>'
            )

    if in_list:
        parts.append("</ul>")
    return "\n".join(parts)


def _build_message(
    settings: Settings,
    recipients: List[str],
    rfq_id: str,
    rfq_title: str,
    changed_text: str,
    requested_by: str,
) -> EmailMessage:
    title = (rfq_title or "").strip() or rfq_id or "an RFQ"
    subject = f"Updated: {title}"[:160]

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = formataddr((settings.email_from_name or "Wootz.Strike", settings.email_from_address))
    # Recipients go in Bcc: a shared list is not an invitation for reply-all,
    # and it keeps one person's address off everyone else's screen.
    msg["To"] = settings.email_from_address
    msg["Bcc"] = ", ".join(recipients)
    if settings.email_reply_to:
        msg["Reply-To"] = settings.email_reply_to

    by = (requested_by or "").strip()
    attribution = f"Regenerated by {by}." if by else "The summary was regenerated."

    plain = (
        f"{title}\n\n"
        f"{attribution} This is what moved since the previous version.\n\n"
        f"{(changed_text or '').strip()}\n\n"
        f"Open the RFQ in Strike for the full summary.\n"
    )
    msg.set_content(plain)

    msg.add_alternative(
        f"""<div style="font-family:Arial,Helvetica,sans-serif; background:#f6f7f8; padding:24px;">
  <div style="max-width:600px; margin:0 auto; background:#ffffff; border:1px solid #e0e4e9;
              border-top:3px solid #4a6178; padding:28px 32px;">
    <p style="margin:0 0 6px 0; font-size:11px; letter-spacing:1.4px; text-transform:uppercase;
              color:#4a6178; font-weight:bold;">Strike &middot; RFQ updated</p>
    <p style="margin:0 0 18px 0; font-size:20px; line-height:28px; color:#1f2328;">{html.escape(title)}</p>
    <p style="margin:0 0 18px 0; font-size:14px; line-height:22px; color:#5f6570;">
      {html.escape(attribution)} This is what moved since the previous version.
    </p>
    <div style="border-left:3px solid #4a6178; background:#eef1f4; padding:18px 20px;">
      {_markdown_to_html(changed_text)}
    </div>
    <p style="margin:20px 0 0 0; font-size:14px; line-height:22px; color:#71777f;">
      Open the RFQ in Strike for the full summary.
    </p>
  </div>
</div>""",
        subtype="html",
    )
    return msg


def send_change_notification(
    settings: Settings,
    rfq_id: str,
    rfq_title: str,
    changed_text: str,
    shared_members: object,
    requested_by: str = "",
) -> int:
    """
    Mail the shared members that something material changed.

    Returns how many addresses it went to; 0 means nothing was sent, which is
    a normal outcome and never an error. Sends only when there is a change to
    report: an unchanged regeneration must not generate mail, or the mail stops
    being read.
    """
    if not settings.enable_regenerate_email:
        return 0

    changed = (changed_text or "").strip()
    if not changed:
        return 0

    recipients = parse_recipients(shared_members)
    if not recipients:
        return 0

    host = (settings.smtp_host or "").strip()
    sender = (settings.email_from_address or "").strip()
    if not host or not sender:
        print(
            "[WARN] email | change to report but SMTP is not configured "
            "(need SMTP_HOST and EMAIL_FROM_ADDRESS) — not sent"
        )
        return 0

    msg = _build_message(settings, recipients, rfq_id, rfq_title, changed, requested_by)

    try:
        if settings.smtp_use_ssl:
            server = smtplib.SMTP_SSL(host, settings.smtp_port, timeout=settings.smtp_timeout_sec,
                                      context=ssl.create_default_context())
        else:
            server = smtplib.SMTP(host, settings.smtp_port, timeout=settings.smtp_timeout_sec)
        with server:
            if settings.smtp_use_tls and not settings.smtp_use_ssl:
                server.starttls(context=ssl.create_default_context())
            if settings.smtp_user:
                server.login(settings.smtp_user, settings.smtp_password)
            server.send_message(msg)
    except Exception as e:
        # A failed notification is not a failed regeneration.
        print(f"[WARN] email | could not notify {len(recipients)} member(s): {type(e).__name__}: {e}")
        return 0

    print(f"[INFO] email | change notification sent to {len(recipients)} member(s) for rfq={rfq_id}")
    return len(recipients)
